""" Setup Vundle =======================
set nocompatible " required for Vundle
filetype off     " required for Vundle

autocmd filetype crontab setlocal nobackup nowritebackup

" Initialize vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle.  Required
Plugin 'gmarik/Vundle.vim'

""""""" Ruby
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-endwise'

"""""" Elixir && Erlang
Plugin 'elixir-lang/vim-elixir'
Plugin 'slashmili/alchemist.vim'
 let g:alchemist_tag_disable = 1
Plugin 'vim-erlang/vim-erlang-runtime'

""""""" Golang
Plugin 'fatih/vim-go'
  let g:go_disable_autoinstall = 0
  " Highlight
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_operators = 1

Plugin 'nsf/gocode', {'rtp': 'vim/'}
Plugin 'jodosha/vim-godebug'

""""""" JavaScript
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
 let g:jsx_ext_required = 0 " Allow JSX in normal JS files

""""""" CSS
Plugin 'JulesWang/css.vim'

""""" Filetypes ========================
"Plugin 'Shougo/neocomplete.vim'
  ""Note: This option must be set in .vimrc(_vimrc).  NOT IN .gvimrc(_gvimrc)!
  "" Disable AutoComplPop.
  "let g:acp_enableAtStartup = 0
  "" Use neocomplete.
  "let g:neocomplete#enable_at_startup = 1
  "" Use smartcase.
  "let g:neocomplete#enable_smart_case = 1
Plugin 'Valloric/YouCompleteMe'

"""""" Development
Plugin 'sheerun/vim-polyglot'
Plugin 'ludovicchabant/vim-gutentags'
 let g:gutentags_cache_dir = '~/.tags_cache'
Plugin 'benekastah/neomake'
 autocmd BufWritePost * Neomake

""""""" lint
Plugin 'scrooloose/syntastic'
  let g:syntastic_check_on_open = 1
  let g:syntastic_check_on_wq = 0
  let g:syntastic_javascript_checkers = ['eslint', 'jsxhint']

""""" Utilities ========================
Plugin 'mileszs/ack.vim'
 let g:ackprg = 'ag --nogroup --nocolor --column'

Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/nerdcommenter'
Plugin 'junegunn/vim-easy-align'
""""" End Utilities ====================

""""" UI Plugins =======================
Plugin 'morhetz/gruvbox'
Plugin 'joshdick/onedark.vim'
""""" End UI Plugins ===================

""""" UI Plugins =======================
Plugin 'bling/vim-airline'       " UI statusbar niceties
 set laststatus=2               " enable airline even if no splits
 let g:airline_theme='base16'
 let g:airline_powerline_fonts = 1
 let g:airline#extensions#hunks#enabled = 0
 let g:airline#extensions#whitespace#enabled = 0
 let g:airline_powerline_fonts = 1
Plugin 'vim-airline/vim-airline-themes'
Plugin 'dandorman/vim-colors'
"""""" End UI Plugins ===================

"""""" Code Navigation ===============
Plugin 'kien/ctrlp.vim'
 let g:ctrlp_match_window_bottom = 1    " Show at bottom of window
 let g:ctrlp_working_path_mode = 'ra'   " Our working path is our VCS project or the current directory
 let g:ctrlp_mru_files = 1              " Enable Most Recently Used files feature
 let g:ctrlp_jump_to_buffer = 2         " Jump to tab AND buffer if already open
 let g:ctrlp_open_multiple_files = 'vr' " opens multiple selections in vertical splits to the right
 let g:ctrlp_arg_map = 0
 let g:ctrlp_dotfiles = 0               " do not show (.) dotfiles in match list
 let g:ctrlp_showhidden = 0             " do not show hidden files in match list
 let g:ctrlp_max_height = 40            " restrict match list to a maxheight of 40
 let g:ctrlp_use_caching = 0            " don't cache, we want new list immediately each time
 let g:ctrlp_max_files = 0              " no restriction on results/file list
 let g:ctrlp_custom_ignore = {
       \ 'dir':  '\v[\/](node_modules|\.(git|hg|svn|gitkeep))$',
       \ 'file': '\v\.(exe|so|dll|log|gif|jpg|jpeg|png|psd|DS_Store|ctags|gitattributes)$'
       \ }

Plugin 'scrooloose/nerdtree'

"""""""" Config
Plugin 'editorconfig/editorconfig-vim'

"""""" End Code Navigation ===========

call vundle#end() " required for Vundle

" Turn on plugins, indentation, etc.
filetype plugin on
filetype plugin indent on
""" End setup Vundle ===================

""" UI Tweaks ==========================
syntax on
set regexpengine=1
set encoding=utf-8
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
set number
"set relativenumber
set sm "括號配對情況
set selection=inclusive
set wildmenu
set laststatus=2
set vb "turn off visual bell
syntax on

set cursorline
"set cursorcolumn

if (has("gui_running"))
  set nowrap
  set guioptions-=b
  set guioptions-=r
  set guioptions-=L
  set background=dark
  "colorscheme gruvbox
  colorscheme onedark
  set guioptions-=T
  set guioptions-=m
  set guifont=hack:h14
else
  set wrap
  set background=dark
  colorscheme onedark
endif
