""" Setup Vundle =======================
set nocompatible " required for Vundle
filetype off     " required for Vundle

autocmd filetype crontab setlocal nobackup nowritebackup

" Initialize vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle.  Required
Plugin 'gmarik/Vundle.vim'

""""""" Utilities
"Plugin 'vim-scripts/taglist.vim'
Plugin 'rizzatti/dash.vim' " Dash Integration

""""" Filetypes ========================
Plugin 'Valloric/YouCompleteMe'

""""""" Ruby
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-endwise'

"lint
Plugin 'scrooloose/syntastic'

""""""" Elixir
Plugin 'elixir-lang/vim-elixir'

""""""" Golang
Plugin 'fatih/vim-go'

""""""" JavaScript
"Plugin 'Shutnik/jshint2.vim'
Plugin 'mxw/vim-jsx'

""""""" CSS
Plugin 'JulesWang/css.vim'

""""" Utilities ========================
Plugin 'honza/vim-snippets'
Plugin 'mileszs/ack.vim'
  let g:ackprg = 'ag --nogroup --nocolor --column'

Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/nerdcommenter'
""""" End Utilities ====================

""""" UI Plugins =======================
Plugin 'morhetz/gruvbox'
""""" End UI Plugins ===================

""""" UI Plugins =======================
Plugin 'bling/vim-airline'       " UI statusbar niceties
  set laststatus=2               " enable airline even if no splits
  let g:airline_theme='gruvbox'
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#hunks#enabled = 0
  let g:airline#extensions#whitespace#enabled = 0
  let g:airline_powerline_fonts = 1
Plugin 'dandorman/vim-colors'
"""""" End UI Plugins ===================

"""""" Code Navigation ===============
Plugin 'kien/ctrlp.vim'
  let g:ctrlp_match_window_bottom = 1    " Show at bottom of window
  let g:ctrlp_working_path_mode = 'ra'   " Our working path is our VCS project or the current directory
  let g:ctrlp_mru_files = 1              " Enable Most Recently Used files feature
  let g:ctrlp_jump_to_buffer = 2         " Jump to tab AND buffer if already open
  let g:ctrlp_open_multiple_files = 'vr' " opens multiple selections in vertical splits to the right
  let g:ctrlp_arg_map = 0
  let g:ctrlp_dotfiles = 0               " do not show (.) dotfiles in match list
  let g:ctrlp_showhidden = 0             " do not show hidden files in match list
  let g:ctrlp_max_height = 40            " restrict match list to a maxheight of 40
  let g:ctrlp_use_caching = 0            " don't cache, we want new list immediately each time
  let g:ctrlp_max_files = 0              " no restriction on results/file list
  let g:ctrlp_custom_ignore = {
        \ 'dir':  '\v[\/](node_modules|\.(git|hg|svn|gitkeep))$',
        \ 'file': '\v\.(exe|so|dll|log|gif|jpg|jpeg|png|psd|DS_Store|ctags|gitattributes)$'
        \ }

Plugin 'scrooloose/nerdtree'

"""""""" Config
Plugin 'editorconfig/editorconfig-vim'

"""""" End Code Navigation ===========

call vundle#end() " required for Vundle

" Turn on plugins, indentation, etc.
filetype plugin on
filetype plugin indent on
""" End setup Vundle ===================

""" UI Tweaks ==========================
"""set relativenumber
set number " line numbering
set t_Co=256 " Force 256 colors

set background=dark
syntax enable
colorscheme gruvbox
set enc=utf-8
set term=screen-256color
let $TERM='screen-256color'

" Highlighting line or number follows....
"set cul " highlight current line

" Highlight current column
"set cuc

" Start scrolling 3 lines before the border
set scrolloff=3

" Whitespace stuff
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

""" Auto Commands ======================
""""" Normalization ====================
" Delete trailing white space on save
func! DeleteTrailingWS()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc
au BufWrite * silent call DeleteTrailingWS()
""""" End Normalization ================
""" End Auto Commands ==================
